### ISSUE TITLE
Folder name declaration in structure

### ISSUE THREAD

**Issue by Brydom** [Huuums/vscode-fast-folder-structure#18]
I think it would be useful to be able to explicitly declare a folder name -- I think that would evolve this tool from 'build a component' to 'speed up your workflow.'

Suggestion:

```json
      "fastFolderStructure.structures": [
        {
          "name": "Component",
          "structure": [
            {
              V--- this would go into ./<Component>/...
              "fileName": "./<FSSName | lowercase>/style.scss"
            },
            {
              V--- this would go into ./, a sibling to <Component>
              "fileName": "./index.js",
              "template": "Component File"
            }
          ]
        }
      ],
```

This would promote the following:
1. Allow creation of items outside of the initial folder we're creating, and totally exclude the folder we're creating if we don't declare `FSSName` in any of the structural items
2. Allow transforming of the folder name -- this would enable you to, ultimately, have whatever you want as your 'component name' (in addition to my next issue) and be able to have it be formatted properly in each scenario

**This would most likely be a breaking change. Having to require the `FSSName` in the structure would bork old versions and put the children somewhere they shouldn't be**

**Comment by UserAnon91** [comment]
I did some Monday morning testing with this, and despite my currently simple setup I can see huge value in this for simplifying file-structure for templates.

I currently have

```
 "fastFolderStructure.structures": [
         {
             "name": "ROBO Test Directory Create",
             "structure": [
                 {
                     "fileName": "/expected/<functionDirectory>/<functionName>/snippets",
                     "template": "EmptyDirectory"
                 },
                 {
                     "fileName": "/expected/<functionDirectory>/<functionName>/sections",
                     "template": "EmptyDirectory"
                 },
                 {
                     "fileName": "/original/sections",
                     "template": "EmptyDirectory"
                 },
                 {
                     "fileName": "/original/snippets",
                     "template": "EmptyDirectory"
                 }
             ],
             "customVariables":[
                 "functionDirectory",
                 "functionName",
             ]
         }
     ]
```

**Comment by Huuums** [comment]
Thanks for reaching out! Sounds like a valid request you have there.

Since this would be a breaking change I'm thinking about adding a new opt-in configuration ( `"fastFolderStructure.disableAutomaticComponentFolderCreation"` or something like that) which would force you to define every folder yourself but also give you more freedom in customization. I'd like to prevent the tool from breaking for existing users that do not need this feature, as I personally feel like this would be used less than the default.

But for now if I understood you correctly you could do
```json
{
      "name": "TS React Functional Component",
      "customVariables": ["customVar1"],
      "structure": [
        {
          "fileName": "<FFSName>.tsx",
          "template": "TS React Functional Component"
        },
        {
          //note the ../ at the start of the path 
          "fileName": "../expected/<customVar1>.test.ts"
        },
        {
          "fileName": "index.ts",
        }
      ]
    },
```
This would create a structure like this 

```
components
    componentName
        componentName.tsx
        index.ts
    expected
        variable.test.ts
```

I understand that the componentName folder is still forcibly created with this even when nothing is in there but maybe it helps a little until I find the time to implement this.

**Comment by Huuums** [comment]
@UserAnon91 
> Once I start implementing file templates there's going to be a lot of repeat directory declaration which can be simplified with this suggestion. I'm all for it!

Could you please elaborate a little more if you don't mind? I don't think I understand what you mean with repeat directory declaration

**Comment by Brydom** [comment]
Come to think of it, I think I imagined this incorrectly. This may only be useful for cases where you don't want a folder template, but strictly a file template (provided you can use `../` already in the structure.)

**Comment by UserAnon91** [comment]
Ah, my mistake, after re-reading the suggestion I realize the suggestion is for creating files directly within the directory that was selected, rather than creating a sub-directory each time.

My thought was allowing for the equivalent to a %path% variable which would shorten declarations for directories within the declarations.

eg;

<pathEquivalent> would be equal to `/<FFSName>/someDirectory/DirectoryAgain/ThirdDirectoryAgain`

such that it can be used as
```
<pathEquivalent>/somefile.js
<pathEquivalent>/testfile1.html
<pathEquivalent>/testFile2.cs
```

resulting in
`/<FFSName>/someDirectory/DirectoryAgain/ThirdDirectoryAgain/somefile.js`
etc

Useful for overly complex file-structures like I'm currently working in, but likely not something everyone would need

**Comment by Huuums** [comment]
@UserAnon91 your use case is probably a rare one as you said yourself. 
I also think that we might get into "configuration for configuration sake" territory.

Defining new templates is something you do once every project or maybe even less so I don't think it's so bothersome as to give the possibility to reuse paths for 

That being said, I do encourage you to create a new Issue for your request and if some more people chip in and say they would welcome this I will add a way to reuse paths.

I will keep this open as well since I do see a use in the ability to define your structure more freely.
